import type { Trip, User, Conversation, Booking, Notification, Review, Message } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Marie Dupont",
    email: "marie.dupont@email.com",
    phone: "+33 6 12 34 56 78",
    whatsapp: "33612345678",
    avatar: "/professional-woman-portrait.png",
    bio: "Voyageuse régulière entre Paris et Dakar. Fiable et ponctuelle.",
    rating: 4.8,
    reviewCount: 24,
    verified: true,
    createdAt: new Date("2023-06-15"),
    languages: ["Français", "Anglais"],
    responseRate: 98,
    responseTime: "< 1h",
  },
  {
    id: "2",
    name: "Ahmed Ben Ali",
    email: "ahmed.benali@email.com",
    phone: "+33 7 98 76 54 32",
    whatsapp: "33798765432",
    avatar: "/professional-man-portrait.png",
    bio: "Plus de 100 livraisons réussies. Service premium garanti.",
    rating: 4.9,
    reviewCount: 56,
    verified: true,
    createdAt: new Date("2022-03-20"),
    languages: ["Français", "Arabe", "Anglais"],
    responseRate: 100,
    responseTime: "< 30min",
  },
  {
    id: "3",
    name: "Sophie Martin",
    avatar: "/young-woman-smiling-portrait.png",
    whatsapp: "33655443322",
    rating: 4.6,
    reviewCount: 12,
    verified: false,
    createdAt: new Date("2024-01-10"),
    languages: ["Français"],
    responseRate: 85,
    responseTime: "< 2h",
  },
  {
    id: "4",
    name: "Karim Ouedraogo",
    avatar: "/african-man-professional-portrait.png",
    bio: "Voyageur expérimenté. Plus de 100 livraisons réussies.",
    whatsapp: "22670112233",
    rating: 5.0,
    reviewCount: 89,
    verified: true,
    createdAt: new Date("2021-09-05"),
    languages: ["Français", "Mooré"],
    responseRate: 99,
    responseTime: "< 1h",
  },
  {
    id: "5",
    name: "Elena Rodriguez",
    avatar: "/latina-woman-portrait.png",
    whatsapp: "34612345678",
    rating: 4.7,
    reviewCount: 31,
    verified: true,
    createdAt: new Date("2023-11-22"),
    languages: ["Français", "Espagnol"],
    responseRate: 92,
    responseTime: "< 1h",
  },
]

export const mockBookings: Booking[] = [
  {
    id: "b1",
    tripId: "1",
    senderId: "2",
    sender: mockUsers[1],
    kgRequested: 5,
    kgConfirmed: 5,
    totalPrice: 60,
    status: "confirmed",
    itemDescription: "Vêtements et chaussures",
    createdAt: new Date("2024-12-28"),
    updatedAt: new Date("2024-12-29"),
  },
  {
    id: "b2",
    tripId: "1",
    senderId: "3",
    sender: mockUsers[2],
    kgRequested: 3,
    totalPrice: 36,
    status: "pending",
    itemDescription: "Documents importants",
    createdAt: new Date("2024-12-30"),
    updatedAt: new Date("2024-12-30"),
  },
  {
    id: "b3",
    tripId: "1",
    senderId: "4",
    sender: mockUsers[3],
    kgRequested: 7,
    kgConfirmed: 7,
    totalPrice: 84,
    status: "in_transit",
    itemDescription: "Électronique (téléphones)",
    createdAt: new Date("2024-12-25"),
    updatedAt: new Date("2025-01-02"),
  },
  {
    id: "b4",
    tripId: "2",
    senderId: "1",
    sender: mockUsers[0],
    kgRequested: 10,
    kgConfirmed: 10,
    totalPrice: 100,
    status: "delivered",
    itemDescription: "Colis divers",
    createdAt: new Date("2024-12-20"),
    updatedAt: new Date("2025-01-05"),
  },
]

export const mockTrips: Trip[] = [
  {
    id: "1",
    userId: "1",
    user: mockUsers[0],
    departure: "Paris",
    departureCountry: "France",
    arrival: "Dakar",
    arrivalCountry: "Sénégal",
    departureDate: new Date("2025-01-15"),
    availableKg: 15,
    totalKg: 30,
    pricePerKg: 12,
    currency: "€",
    description: "Voyage régulier. J'accepte les colis bien emballés. Remise en main propre à Dakar centre.",
    acceptedItems: ["Vêtements", "Électronique", "Documents", "Médicaments"],
    rejectedItems: ["Liquides", "Nourriture périssable"],
    createdAt: new Date("2024-12-20"),
    status: "active",
    bookings: mockBookings.filter((b) => b.tripId === "1"),
    views: 234,
    inquiries: 12,
  },
  {
    id: "2",
    userId: "2",
    user: mockUsers[1],
    departure: "Casablanca",
    departureCountry: "Maroc",
    arrival: "Paris",
    arrivalCountry: "France",
    departureDate: new Date("2025-01-20"),
    availableKg: 23,
    totalKg: 30,
    pricePerKg: 10,
    currency: "€",
    description: "Vol direct Royal Air Maroc. Disponible pour récupération à Casablanca ou Rabat.",
    acceptedItems: ["Vêtements", "Chaussures", "Accessoires", "Livres"],
    rejectedItems: ["Objets de valeur non déclarés"],
    createdAt: new Date("2024-12-22"),
    status: "active",
    views: 189,
    inquiries: 8,
  },
  {
    id: "3",
    userId: "1",
    user: mockUsers[0],
    departure: "Lyon",
    departureCountry: "France",
    arrival: "Abidjan",
    arrivalCountry: "Côte d'Ivoire",
    departureDate: new Date("2025-01-25"),
    availableKg: 8,
    totalKg: 20,
    pricePerKg: 15,
    currency: "€",
    description: "Premier voyage vers Abidjan. Petit espace disponible.",
    acceptedItems: ["Documents", "Petits colis"],
    rejectedItems: ["Colis volumineux", "Liquides"],
    createdAt: new Date("2024-12-25"),
    status: "active",
    views: 67,
    inquiries: 3,
  },
  {
    id: "4",
    userId: "4",
    user: mockUsers[3],
    departure: "Bruxelles",
    departureCountry: "Belgique",
    arrival: "Ouagadougou",
    arrivalCountry: "Burkina Faso",
    departureDate: new Date("2025-02-01"),
    availableKg: 30,
    totalKg: 30,
    pricePerKg: 8,
    currency: "€",
    description: "Voyageur expérimenté. Plus de 100 livraisons réussies. Service fiable et ponctuel.",
    acceptedItems: ["Tout type de colis légaux", "Électronique", "Vêtements", "Médicaments"],
    rejectedItems: ["Produits illégaux"],
    createdAt: new Date("2024-12-28"),
    status: "active",
    views: 312,
    inquiries: 18,
  },
  {
    id: "5",
    userId: "1",
    user: mockUsers[0],
    departure: "Madrid",
    departureCountry: "Espagne",
    arrival: "Bamako",
    arrivalCountry: "Mali",
    departureDate: new Date("2024-12-01"),
    availableKg: 0,
    totalKg: 20,
    pricePerKg: 11,
    currency: "€",
    description: "Voyage terminé avec succès.",
    acceptedItems: ["Vêtements", "Électronique", "Cosmétiques"],
    rejectedItems: ["Nourriture", "Liquides"],
    createdAt: new Date("2024-11-15"),
    status: "completed",
    views: 456,
    inquiries: 25,
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    userId: "1",
    type: "booking",
    title: "Nouvelle réservation",
    message: "Sophie Martin souhaite réserver 3 kg sur votre trajet Paris → Dakar",
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 30), // 30 min ago
    link: "/dashboard/bookings/b2",
    metadata: {
      tripId: "1",
      bookingId: "b2",
      senderName: "Sophie Martin",
      senderAvatar: "/young-woman-smiling.png",
    },
  },
  {
    id: "n2",
    userId: "1",
    type: "message",
    title: "Nouveau message",
    message: "Ahmed Ben Ali vous a envoyé un message",
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2), // 2h ago
    link: "/messages",
    metadata: {
      senderId: "2",
      senderName: "Ahmed Ben Ali",
      senderAvatar: "/professional-man.jpg",
    },
  },
  {
    id: "n3",
    userId: "1",
    type: "review",
    title: "Nouvel avis",
    message: "Karim Ouedraogo vous a laissé un avis 5 étoiles",
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24), // 1 day ago
    link: "/profile/reviews",
    metadata: {
      senderName: "Karim Ouedraogo",
      senderAvatar: "/thoughtful-african-man.png",
    },
  },
  {
    id: "n4",
    userId: "1",
    type: "payment",
    title: "Paiement reçu",
    message: "Vous avez reçu 84€ pour votre livraison",
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48), // 2 days ago
    link: "/profile/payments",
  },
  {
    id: "n5",
    userId: "1",
    type: "reminder",
    title: "Rappel de voyage",
    message: "Votre trajet Paris → Dakar est prévu dans 3 jours",
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3), // 3h ago
    link: "/trips/1",
    metadata: {
      tripId: "1",
    },
  },
  {
    id: "n6",
    userId: "1",
    type: "system",
    title: "Profil vérifié",
    message: "Félicitations ! Votre profil a été vérifié avec succès",
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72), // 3 days ago
  },
]

export const mockReviews: Review[] = [
  {
    id: "r1",
    tripId: "5",
    reviewerId: "4",
    reviewer: mockUsers[3],
    reviewedId: "1",
    rating: 5,
    comment: "Service impeccable ! Marie est très professionnelle et ponctuelle. Je recommande vivement.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
  {
    id: "r2",
    tripId: "5",
    reviewerId: "2",
    reviewer: mockUsers[1],
    reviewedId: "1",
    rating: 5,
    comment: "Excellent service, communication parfaite. Colis livré dans les temps.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
  },
  {
    id: "r3",
    tripId: "5",
    reviewerId: "5",
    reviewer: mockUsers[4],
    reviewedId: "1",
    rating: 4,
    comment: "Très bon service. Petit retard à la livraison mais tout s'est bien passé.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72),
  },
  {
    id: "r4",
    tripId: "5",
    reviewerId: "1",
    reviewer: mockUsers[0],
    reviewedId: "4",
    rating: 5,
    comment: "Client très sérieux, colis bien préparé et à l'heure au point de rendez-vous. Parfait !",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 20),
  },
  {
    id: "r5",
    tripId: "2",
    reviewerId: "1",
    reviewer: mockUsers[0],
    reviewedId: "2",
    rating: 5,
    comment: "Ahmed est un expéditeur exemplaire. Communication claire et colis impeccable.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96),
  },
]

const mockMessages: Message[] = [
  {
    id: "m1",
    senderId: "2",
    receiverId: "1",
    tripId: "1",
    content: "Bonjour ! Je suis intéressé par votre offre de kilos vers Dakar.",
    createdAt: new Date("2024-12-29T14:30:00"),
    read: true,
    type: "text",
  },
  {
    id: "m2",
    senderId: "1",
    receiverId: "2",
    tripId: "1",
    content: "Bonjour Ahmed ! Oui, j'ai encore 15kg de disponibles. Quel type de colis souhaitez-vous envoyer ?",
    createdAt: new Date("2024-12-29T14:32:00"),
    read: true,
    type: "text",
  },
  {
    id: "m3",
    senderId: "2",
    receiverId: "1",
    tripId: "1",
    content: "Ce sont des vêtements et quelques appareils électroniques, environ 5kg au total. C'est possible ?",
    createdAt: new Date("2024-12-29T14:35:00"),
    read: true,
    type: "text",
  },
  {
    id: "m4",
    senderId: "1",
    receiverId: "2",
    tripId: "1",
    content: "Parfait, c'est tout à fait possible ! Pour l'électronique, assurez-vous que tout soit bien emballé.",
    createdAt: new Date("2024-12-29T14:38:00"),
    read: true,
    type: "text",
  },
  {
    id: "m5",
    senderId: "2",
    receiverId: "1",
    tripId: "1",
    content: "Super ! Comment procède-t-on pour la remise du colis ?",
    createdAt: new Date("2024-12-29T14:40:00"),
    read: false,
    type: "text",
  },
]

export const mockConversations: Conversation[] = [
  {
    id: "1",
    tripId: "1",
    trip: mockTrips[0],
    participants: [mockUsers[1], mockUsers[0]],
    messages: mockMessages,
    lastMessage: mockMessages[mockMessages.length - 1],
    unreadCount: 1,
    createdAt: new Date("2024-12-29"),
  },
  {
    id: "2",
    tripId: "2",
    trip: mockTrips[1],
    participants: [mockUsers[2], mockUsers[0]],
    messages: [
      {
        id: "m10",
        senderId: "3",
        receiverId: "1",
        tripId: "2",
        content: "Bonjour, vous acceptez les documents administratifs ?",
        createdAt: new Date("2024-12-28T10:00:00"),
        read: true,
        type: "text",
      },
      {
        id: "m11",
        senderId: "1",
        receiverId: "3",
        tripId: "2",
        content: "Oui bien sûr ! Pas de problème pour les documents.",
        createdAt: new Date("2024-12-28T10:15:00"),
        read: true,
        type: "text",
      },
    ],
    lastMessage: {
      id: "m11",
      senderId: "1",
      receiverId: "3",
      tripId: "2",
      content: "Oui bien sûr ! Pas de problème pour les documents.",
      createdAt: new Date("2024-12-28T10:15:00"),
      read: true,
      type: "text",
    },
    unreadCount: 0,
    createdAt: new Date("2024-12-28"),
  },
  {
    id: "3",
    tripId: "3",
    trip: mockTrips[2],
    participants: [mockUsers[4], mockUsers[0]],
    messages: [
      {
        id: "m20",
        senderId: "5",
        receiverId: "1",
        tripId: "3",
        content: "Salut ! Il te reste combien de kg disponibles ?",
        createdAt: new Date("2024-12-30T16:00:00"),
        read: false,
        type: "text",
      },
    ],
    lastMessage: {
      id: "m20",
      senderId: "5",
      receiverId: "1",
      tripId: "3",
      content: "Salut ! Il te reste combien de kg disponibles ?",
      createdAt: new Date("2024-12-30T16:00:00"),
      read: false,
      type: "text",
    },
    unreadCount: 1,
    createdAt: new Date("2024-12-30"),
  },
]

export const popularRoutes = [
  { from: "Paris", to: "Dakar", count: 156 },
  { from: "Paris", to: "Abidjan", count: 124 },
  { from: "Bruxelles", to: "Kinshasa", count: 98 },
  { from: "Lyon", to: "Casablanca", count: 87 },
  { from: "Paris", to: "Bamako", count: 76 },
]

export const countries = [
  "France",
  "Sénégal",
  "Maroc",
  "Côte d'Ivoire",
  "Mali",
  "Burkina Faso",
  "Belgique",
  "Espagne",
  "Cameroun",
  "RD Congo",
  "Tunisie",
  "Algérie",
  "Guinée",
  "Togo",
  "Bénin",
  "Niger",
  "Mauritanie",
  "Gabon",
]

export const cities: Record<string, string[]> = {
  France: ["Paris", "Lyon", "Marseille", "Toulouse", "Nice", "Bordeaux"],
  Sénégal: ["Dakar", "Thiès", "Saint-Louis", "Ziguinchor"],
  Maroc: ["Casablanca", "Rabat", "Marrakech", "Fès", "Tanger"],
  "Côte d'Ivoire": ["Abidjan", "Bouaké", "Yamoussoukro"],
  Mali: ["Bamako", "Sikasso", "Mopti"],
  "Burkina Faso": ["Ouagadougou", "Bobo-Dioulasso"],
  Belgique: ["Bruxelles", "Anvers", "Liège"],
  Espagne: ["Madrid", "Barcelone", "Valence"],
}
